on:
  workflow_dispatch:
  push:
    branches:
      - main-next

jobs:
  test:
    runs-on: docker
    container:
      image: codeberg.org/larchcone/ci/node:20-custom
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - run: |
          ulimit -t 10 # kill QEMU after 10 seconds CPU time
          ARCH=aarch64 make clean run
