on:
  workflow_dispatch:
  push:
    branches:
      - main-next

jobs:
  test:
    runs-on: docker
    container:
      image: codeberg.org/larchcone/ci/node:20-custom
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - run: ls -la