on:
  workflow_dispatch:
  push:
    branches:
      - main-next

jobs:
  test:
    runs-on: docker
    container:
      image: codeberg.org/larchcone/ci/node:20-custom
    steps:
      - run: uname -a
      - run: free -h
      - run: dpkg -l | grep qemu